name: Robot Framework CI

on:
  push:
    branches:
      - main

jobs:
    Run-Test:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v3
        - name: Install pip dependencies
          run: |
            pip install --upgrade pip
            pip install -r requirement.txt
        - name: Run Test
          run: robot -d reports .\tests\test_authentification.robot .\tests\test_creation_contrat_credit.robot